### PR TITLE
Handle the directive literal

### PR DESCRIPTION
**Pull request by dennwc**
Handle the directive literal and rename the `valueNorm` (the field we create) to `value` to be more consistent with the native AST.

Signed-off-by: Denys Smirnov <denys@sourced.tech>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/javascript-driver/85)

### CODE REVIEW

**Comment by bzz** [comment]
@dennwc I feel that this is quite a big change in one of our most-used (at least internally) drivers - could you please explain a bit more about rationale of including the `"` in the token of the string literals in semantic mode? Thanks!

**Comment by creachadair** [comment]
> The notion is that we are basically splitting the semantics of a node into two sub-nodes that are "orthogonal" in their meaning.

It makes sense—but I think of these axes in terms of the complex number plane: Syntactic changes move in the real axis, semantic annotations move in the imaginary axis. 

I think it's important for a query to be able to move along each of these dimensions independently, so it's clear whether you are getting annotations or structure (or of course both). Splitting nodes seems fine as long as a query can express "only traverse real paths" or "only traverse imaginary paths" in some way.

**Comment by dennwc** [comment]
So yeah, the question boils down to a query language anyway. For XPath we will have to split nodes, since we can't change the way it works that much (or it's rather impractical).

**Comment by bzz** [comment]
Thank you for explaining, @dennwc! If that is ok, I would like to take a bit more time to understand the change better, as well as it's impact on the downstream users of js driver.

**Comment by creachadair** [comment]
> So yeah, the question boils down to a query language anyway. For XPath we will have to split nodes, since we can't change the way it works that much (or it's rather impractical).

You're right, the mapping to XPath does complicate the picture a bit. If the data model makes a clean distinction between attributes and structure, though, we could update the XPath mapping to consider only structure (say), which would keep old queries working while allowing new information into the graph. In the long run I think we all agree we'll need a more expressive query interface than XPath anyway, so it seems to me the important question is how to keep XPath from degrading too much as we work toward it 😄.

**Pull request merged**
