### PR TITLE
Upgrade JS package dependencies (yarn upgrade).

### PR DESCRIPTION
**Pull request by creachadair**
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/javascript-driver/90)

### CODE REVIEW

**Comment by creachadair** [comment]
Unfortunately, it looks like I'm going to have to split the Babel upgrade from the rest of this change; there are just too many AST changes and no clear documentation as to what the API guarantees.

**Comment by bzz** [comment]
> it looks like I'm going to have to split the Babel upgrade from the rest of this change; 
🙏 and we conveniently have https://github.com/bblfsh/javascript-driver/issues/47 for it

**Comment by creachadair** [comment]
I surveyed the diffs between the existing native fixtures and those generated by the new version of the parser. As far as I can tell, all of the differences are the addition of one or more of the following properties:

```
inexact: bool
internalSlots: []
interpreter: ~
leadingComments: ~
method: bool
proto: bool
```

This seems to be a straightforward metadata extension of some kind, and I think it should be safe to update the fixtures on that basis. @dennwc do you think that is reasonable?

**Comment by creachadair** [comment]
> > it looks like I'm going to have to split the Babel upgrade from the rest of this change;
> 
> 🙏 and there conveniently is a #47 for it

Unfortunately, while splitting that part of the change is appealing for reasons of organization, there is no easy way to cut that one piece out: Upgrading Babel also pulls in a whole bunch of other updates, which is more or less what this change does anyway. And those updates are the cause for the rest of the changes in this PR already. Worse, I found that if I leave the old version pinned in place I can't update the packages I _need_ to update to fix the upstream bug. 🤷🏻‍♀️

So I think in practice it will not save anything to separate them.

**Comment by creachadair** [comment]
I have updated the fixtures for the output changes described above. The errors that remain are because the parser is now more strict than it used to be, and will complain for invalid structures like re-definitions of existing names, and exports of non-existing names.

Our existing parser logic has some custom hooks to "guess" which mode to run the parser in ("module" or "script"). An error in the first falls back to the second. This means when we have an invalid file in module mode, we _also_ get an error from script mode. But since script mode cannot handle newer ES constructs like `import` and `export`, that will always fail. I believe the current version of Babel can handle this guesswork by itself. 

My plan for now is to make the fixtures "valid", and to address the fallback weirdness in a separate PR.

**Comment by creachadair** [comment]
I believe this is now ready for a review. While a lot of files are involved, most of the changes are mechanical. The changes that should be reviewed closely are:

1. The files under the `native` directory, including the version locks, `parser.js`, and rollup config. This is the substance of the change, updating the dependencies.

2. The fixture changes to `fixtures/import-declaration.js`, `fixtures/export-declaration.js`, and `fixtures/u2_import_subsymbol.js`, together with their associated golden files. These files needed updates for increased strictness in the `@babel/parser` API.

**Pull request merged**
